package sim

// Example returns three passenger stations and a two-berth parking siding.
func Example() Network {
	return Network{
		Nodes: []Node{
			{ID: "harbor-entry", Position: Point{80, 260}},
			{ID: "harbor-berth", Position: Point{130, 350}},
			{ID: "harbor-exit", Position: Point{200, 260}},
			{ID: "branch", Position: Point{300, 260}},
			{ID: "garden-entry", Position: Point{400, 150}},
			{ID: "garden-berth", Position: Point{480, 70}},
			{ID: "garden-exit", Position: Point{570, 150}},
			{ID: "bypass", Position: Point{470, 300}},
			{ID: "merge", Position: Point{670, 260}},
			{ID: "market-entry", Position: Point{730, 260}},
			{ID: "market-berth", Position: Point{800, 350}},
			{ID: "market-exit", Position: Point{880, 260}},
			{ID: "return-east", Position: Point{900, 460}},
			{ID: "parking-entry", Position: Point{620, 460}},
			{ID: "parking-exit", Position: Point{340, 460}},
			{ID: "parking-berth-1", Position: Point{480, 420}},
			{ID: "parking-berth-2", Position: Point{480, 365}},
			{ID: "return-west", Position: Point{60, 460}},
		},
		Lanes: []Lane{
			{ID: "harbor-through", From: "harbor-entry", To: "harbor-exit", SpeedLimit: 14},
			{ID: "harbor-in", From: "harbor-entry", To: "harbor-berth", SpeedLimit: 14},
			{ID: "harbor-out", From: "harbor-berth", To: "harbor-exit", SpeedLimit: 14},
			{ID: "approach-branch", From: "harbor-exit", To: "branch", SpeedLimit: 14},
			{ID: "garden-approach", From: "branch", To: "garden-entry", SpeedLimit: 14},
			{ID: "garden-through", From: "garden-entry", To: "garden-exit", SpeedLimit: 14},
			{ID: "garden-in", From: "garden-entry", To: "garden-berth", SpeedLimit: 14},
			{ID: "garden-out", From: "garden-berth", To: "garden-exit", SpeedLimit: 14},
			{ID: "garden-merge", From: "garden-exit", To: "merge", SpeedLimit: 14},
			{ID: "bypass-in", From: "branch", To: "bypass", SpeedLimit: 14},
			{ID: "bypass-merge", From: "bypass", To: "merge", SpeedLimit: 14},
			{ID: "market-approach", From: "merge", To: "market-entry", SpeedLimit: 14},
			{ID: "market-through", From: "market-entry", To: "market-exit", SpeedLimit: 14},
			{ID: "market-in", From: "market-entry", To: "market-berth", SpeedLimit: 14},
			{ID: "market-out", From: "market-berth", To: "market-exit", SpeedLimit: 14},
			{ID: "return-start", From: "market-exit", To: "return-east", SpeedLimit: 14},
			{ID: "return-to-parking", From: "return-east", To: "parking-entry", SpeedLimit: 14},
			{ID: "parking-through", From: "parking-entry", To: "parking-exit", SpeedLimit: 14},
			{ID: "parking-in-1", From: "parking-entry", To: "parking-berth-1", SpeedLimit: 14},
			{ID: "parking-out-1", From: "parking-berth-1", To: "parking-exit", SpeedLimit: 14},
			{ID: "parking-in-2", From: "parking-entry", To: "parking-berth-2", SpeedLimit: 14},
			{ID: "parking-out-2", From: "parking-berth-2", To: "parking-exit", SpeedLimit: 14},
			{ID: "return", From: "parking-exit", To: "return-west", SpeedLimit: 14},
			{ID: "harbor-approach", From: "return-west", To: "harbor-entry", SpeedLimit: 14},
		},
		Stations: []Station{
			{ID: "harbor", Name: "Harbor", Entry: "harbor-entry", Exit: "harbor-exit", Berths: []Berth{{ID: "harbor-1", Node: "harbor-berth"}}},
			{ID: "garden", Name: "Garden", Entry: "garden-entry", Exit: "garden-exit", Berths: []Berth{{ID: "garden-1", Node: "garden-berth"}}},
			{ID: "market", Name: "Market", Entry: "market-entry", Exit: "market-exit", Berths: []Berth{{ID: "market-1", Node: "market-berth"}}},
			{ID: "parking", Name: "Parking", Entry: "parking-entry", Exit: "parking-exit", ParkingOnly: true, Berths: []Berth{{ID: "parking-1", Node: "parking-berth-1"}, {ID: "parking-2", Node: "parking-berth-2"}}},
		},
	}
}
